name: Update file in another repository

on:
  workflow_dispatch:

jobs:
  update_file:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository containing the file you want to update
      - uses: actions/checkout@v2
        with:
          repository: fxc775/argocd-app-config
          ref: main
     # Update the file
      - run: |
          echo "Updating file"
          # Replace the image in the file
          sed -i 's/image: nanajanashia\/argocd-app:1.0/image: nanajanashia\/argocd-app:1.1/g' dev/deployment.yaml
          echo "running cat of new file"
          cat dev/deployment.yaml
          git config --local user.email "action@github.com"
          git config --local user.name "fxc775"
          git add dev/deployment.yaml
          git commit -m "Updated deployment.yaml"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
