name: Update file in another repository

on:
  workflow_dispatch:
  
jobs:
  update_file:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository containing the file you want to update
      - uses: actions/checkout@v3
        with:
          repository: fxc775/argocd-app-config
          ref: main
          token: ${{ secrets.PAT_TOKEN }}
     # Update the file
      - name: Update The File with New Image
      - run: |
          echo "Updating file"
          # Replace the image in the file
          sed -i 's/image: nanajanashia\/argocd-app:1.3/image: nanajanashia\/argocd-app:1.4/g' dev/deployment.yaml
     # Commit and push the changes  
      - name: Commit and Push the Changes
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dev/deployment.yaml
          git commit -m "Updated deployment.yaml"
          git push origin main



