name: Update file in another repository

on:
  workflow_dispatch:
  
jobs:
  update_file:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository containing the file you want to update
      - uses: actions/checkout@v3
        with:
          repository: fxc775/argocd-app-config
          ref: main
          token: ${{ secrets.PAT_TOKEN }}
     # Update the file
      - run: |
          echo "Updating file"
          # Replace the image in the file
          sed -i 's/image: nanajanashia\/argocd-app:1.2/image: nanajanashia\/argocd-app:1.3/g' dev/deployment.yaml
     # Update the file   
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dev/deployment.yaml
          git commit -m "Updated deployment.yaml"
          git push origin main



